//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppTacos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TacosDBEntities3 : DbContext
    {
        public TacosDBEntities3()
            : base("name=TacosDBEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asiakkaat> Asiakkaat { get; set; }
        public virtual DbSet<Kirjautuminen> Kirjautuminen { get; set; }
        public virtual DbSet<Tilaukset> Tilaukset { get; set; }
        public virtual DbSet<Tilausrivit> Tilausrivit { get; set; }
        public virtual DbSet<Tuoteryhmat> Tuoteryhmat { get; set; }
        public virtual DbSet<Tuotteet> Tuotteet { get; set; }
        public virtual DbSet<ProductsDailySales> ProductsDailySales { get; set; }
        public virtual DbSet<TilausMaarat> TilausMaarat { get; set; }
        public virtual DbSet<Top10Tuotteet> Top10Tuotteet { get; set; }
        public virtual DbSet<TuotteidenKaikkiMyynnit> TuotteidenKaikkiMyynnit { get; set; }
        public virtual DbSet<TuotteidenPaivaMyynnit> TuotteidenPaivaMyynnit { get; set; }
    }
}
