//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppTacos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TilausMaarat
    {
        public long rowid { get; set; }
        public string Weekday { get; set; }
        public Nullable<decimal> Total { get; set; }
    }
}
