//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppTacos.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Tuoteryhmat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tuoteryhmat()
        {
            this.Tuotteet = new HashSet<Tuotteet>();
        }

        public int TuoteryhmaID { get; set; }
        public string Tuoteryhmanimi { get; set; }
        public string Kuvaus { get; set; }
        public string TuoteryhmaIDtuoteryhmaNimi { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tuotteet> Tuotteet { get; set; }
    }
}
